Autodesk/react-base-table

CHANGELOG.md
src/GridTable.js

`rowHeight` for header `Grid` is a function https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#recomputegridsize--columnindex-number-rowindex-number-

fix header row's height doesn't update on change

---

src/BaseTable.js

The problem: If we set `scrollbarSize = 0` in SSR and use the real size like `scrollbarSize = 15` in client hydration, the layout won't be updated, see https://github.com/facebook/react/issues/8017 https://github.com/facebook/react/issues/10591 https://github.com/facebook/react/issues/11128
So we have to keep the value identical both in SSR and client hydration, and then update the value manually in `cDM`. I know it's not so good for pure client side use case, but I just can't find a way to distinguish it's in hydration or a normal rendering

always do a second render for SSR compatible

---

docs/selection.md
website/siteConfig.js

[website] add doc for selection

---

CHANGELOG.md
package.json
src/BaseTable.js
src/ColumnResizer.js
src/_BaseTable.scss
yarn.lock

ref https://github.com/Autodesk/react-base-table/issues/3#issuecomment-493711970
currently `react-draggble` takes 1/5 of the bundle size
@zmitry FYI

refactor: remove dependency on react-dragable

---

CHANGELOG.md
src/utils.js

that's a regression from #54 which use `dot-prop` to replace `lodash.get`, but `dot-prop` just return the object itself if the path is not valid string

getValue returns the object itself if the path is not valid string

---

CHANGELOG.md
src/BaseTable.js
website/src/utils/baseScope.js

as `findDOMNode` is deprecated in strict mode, it would nice to provide a way to get the DOM node of the table for `createPortal`
you can use `ref.getDOMNode()` outside of table of `container.getDOMNode()` in renders

add getDOMNode method

---

CHANGELOG.md
src/BaseTable.js
src/GridTable.js
website/siteConfig.js
website/src/examples/scroll-to.js

fix the issue described in #76 , that's a regression introduced in #73, the following is the I left for the initial fix to move the methods in a setTimeout:
// if the table is in `fixed` mode, it could be scrolled horizontally, in that case,
// the horizontal scroll position would be unexpected if the `align` is not `start`,
// so we reset the horizontal scroll to the previous value in that case,
// and the two scroll methods would be batched on event callback, and the `onScroll` event will be called after that,
// then it will be reset to the original position as the `this._scroll` is not synced to the new state,
// so we put them in a `setTimeout` to make `onScroll` be called before we set the horizontal position.
but actually it will break in concurrent mode as the batched behavior is …

fix regression of scrollToRow

---

CHANGELOG.md
src/utils.js

the case is we unflatten the data once, and then group(unflatten) the data in some rule, we should keep the former tree structure as well

fix: unflatten should not override the existing children

---

CHANGELOG.md
src/BaseTable.js
src/TableRow.js

fix an issue mentioned here https://github.com/Autodesk/react-base-table/pull/170#issuecomment-647873148
@jamesonhill FYI, I thought the buffer is a genius idea to merge the heights from different tables, but it seems using separate maps to cache is much safer

fix: rowHeight is not calculated correctly with frozen columns

---

CHANGELOG.md
src/BaseTable.js

fix #199 
the bug also happens with `maxHeight`, the cause is that `getTotalRowsHeight` would be call before rendered, so the height is the previous value of `GridTable`

fix: getTotalRowsHeight could be different before/after render in dynamic mode

---

CHANGELOG.md
src/BaseTable.js

fix: getTotalRowsHeight could be different before/after render in dynamic mode again

---

CHANGELOG.md
README.md
src/BaseTable.js
src/utils.js

feat: add ignoreFunctionInColumnCompare to solve closure problem in renderers

---

CHANGELOG.md
package.json
src/BaseTable.js
types/index.d.ts
yarn.lock

Initial pass at adding type declarations for each component's props as well as typings used by various event handlers. Feel free to comment or modify.

feat: add type declarations

---

package.json

Right now the typescript d.ts file is not packaged into the npm bundle, we should include it :P

fix: add types folder into packages

---

CHANGELOG.md
src/Column.js

fix: remove propTypes for Column.key

---

CHANGELOG.md
src/BaseTable.js
src/GridTable.js
src/TableRow.js
src/utils.js
types/index.d.ts

This PR makes possible to pass in `estimatedRowHeight` property a function that called for each row to get initial height of row. This can help to fix "jumping" effect on first rendering when height of rows are known (possible fix #227)

feat: add the ability to pass function in estimatedRowHeight

---

README.md

- included message in README to emphasize importance of importing CSS classes as defined in `react-base-table/styles.css` in order for `BaseTable` to render as advertised in examples

chore: update README.md to emphasize the importance of importing styles

---

website/src/examples/custom-cell.js

`Score` is defined but isn't being used in this example.

website: updating website example

---

CHANGELOG.md
src/BaseTable.js

This PR fix prop-types warnings when using custom components, defined as classes.

fix: change propTypes for BaseTable.components

---

src/TableHeader.js

When my table column component is a custom component, the scrollLeft property always takes a long time when I slide the table.
​
As shown below, when I use Chrome Devtools Performance to analyze the scrolling behavior, Activity -> Layout takes the first place. Through tracking, it is found that the scrollLeft property has been reassigned in the scrollTo function.
​
The browser will calculate the value of the attribute on the spot whether it is assigning or acquiring scrollLeft. Perhaps because the browser layout tree is top-down, calculating scrollLeft is always much slower than calculating scrollTop
Our customized table based on react-base-table has more than 10 columns. So calculating scrollLeft will be slower. On my customized table, scrollLeft can get about 12ms, which is enough to …

fix: optimization render task performance

---

CHANGELOG.md
package.json
src/TableHeader.js

The table heade ref may be undefined on the requestAnimationFrame call
E.g. Uncaught TypeError: Cannot set properties of null (setting 'scrollLeft')
The issue imported from the change at https://github.com/Autodesk/react-base-table/pull/348

fix: table crash on setting scroll

---

CHANGELOG.md
package.json
src/BaseTable.js

Pass sorting status to SortIndicator to support customize icon

fix: pass sorting status to SortIndicator
