Autodesk/react-base-table

- CHANGELOG.md
- src/BaseTable.js
- src/GridTable.js
> stop using forceUpdate

- CHANGELOG.md
- src/BaseTable.js
- src/utils.js
the old recursion version of `unflatten` is extremely slow with large data set
> optimize utlis

- website/siteConfig.js
- website/src/examples/row-span.js
> [website] add row span demo

- website/src/examples/components.js
address the scenario described in #27
> [website] update components demo

- CHANGELOG.md
- src/BaseTable.js
- src/GridTable.js
> allow rowKey to be number

- CHANGELOG.md
- src/BaseTable.js
> add getScrollbarSize for customization

- website/siteConfig.js
- website/src/examples/scrollbar.js
https://github.com/Autodesk/react-base-table/issues/32#issuecomment-491341875
> [website] add scrollbar demo

- CHANGELOG.md
- package.json
- src/GridTable.js
- website/yarn.lock
- yarn.lock
> upgrade react-window to silence the deprecation

- CHANGELOG.md
- src/BaseTable.js
> fix: resizing line rendered incorrectly

- CHANGELOG.md
- src/BaseTable.js
> fix: infinite loading should work with maxHeight

- CHANGELOG.md
- src/BaseTable.js
- src/_BaseTable.scss
- website/siteConfig.js
- website/src/examples/multi-sort.js
close #7 I decide to add a new prop to not break the current behavior
> add sortByMultiple to support multiple sort

- CHANGELOG.md
- src/BaseTable.js
- website/siteConfig.js
- website/src/examples/multi-sort.js
> rename to sortState

- website/package.json
- website/siteConfig.js
- website/src/examples/inline-editing.js
- website/src/utils/baseScope.js
- website/yarn.lock
This is really a rough version, will improve it late
> [docs] add inline editing example

- CHANGELOG.md
- src/BaseTable.js
- src/Column.js
- src/TableHeaderRow.js
- src/TableRow.js
- src/utils.js
> fix: support function component with hooks

- CHANGELOG.md
- src/ColumnResizer.js
touch event support is removed in #56
> fix: bring back column resize on touch support

- CHANGELOG.md
- src/BaseTable.js
remove the use of `componentWillReceiveProps` to make it strict mode ready, and be happy with React V16.9.0
close #10
> chore: remove the use of cWRP

- README.md
- docs/get-started.md
> docs: mention about rowKey

- CHANGELOG.md
- src/BaseTable.js
- website/src/examples/resizable.js
> feat: Added onColumnResizeEnd prop to BaseTable

- README.md
- website/siteConfig.js
- website/src/examples/column-hovering.js
this is the most effective way to show column hovering effect, https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDZm3DQYUIgCN4OAEo4AZn11FgUAHTACOIbr01WSjjADi8EOqLwAylACeWvhZWpC5uHt5+OAAGLDAwpgBCRBA4ACoaWqbGUACWAG44ALQIBQwwANrcakWUBdmcAB7oAEQMTQC6UjFxiclpmjiZJnmFxXTllUTV8LUNzXTtnbEJSanpA1nDUwWy4zxbdY1Nsgtdy71rgzn5WwDMu1XFB803J0s9q-2Xm8UALPeTj1mTR+r26Kz6GQ212KAFZ-vsgTDQWcPpChtCagA2eGAw6Y5HvCHrdEjGoAdhxNSeTTJBPBFyhpOmAA5KdNqcy6edPoytgBONkzQ589owADeXVi7mAAGssAQQIgwJwAFwwADEehuWq1AG4ugBfFjRBwqYA4eDwAAKCoADhA+DQxXBKJIAJLKnD1GAGpgYAB8MCdXQA5BMEfUQ2qJKgPZwvYsYOAALKK5IAUTApAIarsAfFkpdjjU-T4Ja0NnMiAIlizplwUGEAHlkwA5EDxuyF8sDYDwJIQAAy2WgmU4nBokV5xQAJGKY2A416DZFWLEDYmU2mcIOrPlc370IGJbFYuwVD2y2tK8Bq7WzA3m22Ozgu6fVBc+ …
> [website] add column hovering example

- src/BaseTable.js
> fix: frozen data not shown with empty data

- CHANGELOG.md
- src/Column.js
> fix: wrong description for Column props

- website/siteConfig.js
- website/src/examples/draggable-rows-frozen.js
> docs: add draggable rows with frozen columns

- website/package.json
- website/siteConfig.js
- website/src/examples/custom-cell.js
- website/src/utils/baseScope.js
- website/yarn.lock
> [website] add custom cell example

- CHANGELOG.md
- src/BaseTable.js
> fix: dynamic rowHeight is not updated when resizing column

- CHANGELOG.md
- src/BaseTable.js
- src/GridTable.js
> fix: regression of expansion with frozen columns

- CHANGELOG.md
- src/BaseTable.js
- src/TableRow.js
- website/siteConfig.js
- website/src/examples/dynamic-row-heights.js
close #177 and also fixed some other issues
> fix: dynamic rowHeight is not updated when data/columns changed

- src/BaseTable.js
- src/GridTable.js
- website/siteConfig.js
- website/src/examples/detail-view.js
also added a detail-view example to close #140
> fix: horizontal scrollbar in flex mode with dynamic row height

- README.md
> chore: add Development secion to README

- CHANGELOG.md
- src/BaseTable.js
- website/src/examples/custom-cell.js
- website/src/examples/dynamic-row-heights.js
> fix: scroll position would be reset to top if column becomes frozen

- CHANGELOG.md
- src/ColumnResizer.js
> fix: input loses focus on unmount
